### ISSUE TITLE
Website DOWN

### ISSUE THREAD

**Issue by davidak** [danielbachhuber/CoPress-Convert#6]
It seems that the domain has expired.

![screenshot from 2018-11-27 17-22-26](https://user-images.githubusercontent.com/91113/49095571-0c7ff380-f269-11e8-89c3-9ae70b446756.png)

**Comment by danielbachhuber** [comment]
I took the site down a while back

**Comment by davidak** [comment]
@danielbachhuber can you remove the URL from the project then?

**Comment by danielbachhuber** [comment]
> can you remove the URL from the project then?

Sure, done.
